#!/usr/bin/env python3
import os
import sys
import subprocess
import time
from pathlib import Path
from typing import List, Optional, Tuple

import google.generativeai as genai
from github import Github, GithubException

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_FULL_NAME = os.environ.get("REPO_FULL_NAME")
BASE_BRANCH = os.environ.get("BASE_BRANCH", "main")
WORKSPACE = os.environ.get("GITHUB_WORKSPACE") or os.getcwd()
NEW_BRANCH = "gemini-systemic-review"

MODEL_NAME = "gemini-2.0-flash"   # fallback, will be overridden if discovered
TEMPERATURE = 0.2
MAX_OUTPUT_TOKENS = 4096

SYSTEM_PROMPT = """You are an expert Android Kotlin engineer. For every file you review, output the complete corrected file content.
If the file is perfect, output the original content unchanged.
Always prefix the output with `=== FULL FILE: path/to/file.kt ===` on its own line, then the entire file content.
Do not output diffs or explanations outside that block.
Focus on fixing bugs, improving logic, optimizing performance, and adhering to 2026 Android/Kotlin best practices.
Areas: null safety, coroutines, Jetpack Compose, MVVM, performance, security, Gradle version catalogs.
"""

def find_source_files(root_dir: str) -> List[str]:
    extensions = ('.kt', '.java', '.xml', '.gradle', '.kts', '.properties')
    root = Path(root_dir).resolve()
    files = []
    for ext in extensions:
        for p in root.rglob(f"*{ext}"):
            if any(part in p.parts for part in ['build', '.git', 'generated', 'tmp', 'node_modules']):
                continue
            if p.stat().st_size == 0:
                continue
            files.append(str(p.relative_to(root)))
    return sorted(files)

def read_file_content(rel_path: str) -> Optional[str]:
    full_path = os.path.join(WORKSPACE, rel_path)
    try:
        with open(full_path, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception:
        return None

def write_file_content(rel_path: str, content: str):
    full_path = os.path.join(WORKSPACE, rel_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, 'w', encoding='utf-8') as f:
        f.write(content)

def get_available_model() -> str:
    """Return the first available generateContent model."""
    try:
        for m in genai.list_models():
            if 'generateContent' in m.supported_generation_methods:
                return m.name
    except Exception:
        pass
    return "gemini-2.0-flash"

def review_and_fix_file(rel_path: str, content: str, model_name: str) -> Tuple[Optional[str], Optional[str]]:
    user_prompt = f"""Provide the complete corrected version of the following file:
File: {rel_path}
Current content:
{content}

Output exactly as:
=== FULL FILE: {rel_path} ===
<new file content>
"""
    try:
        model = genai.GenerativeModel(
            model_name,
            generation_config={
                "temperature": TEMPERATURE,
                "max_output_tokens": MAX_OUTPUT_TOKENS,
            }
        )
        response = model.generate_content([SYSTEM_PROMPT, user_prompt])
        result = response.text
        marker = f"=== FULL FILE: {rel_path} ==="
        if marker in result:
            new_content = result.split(marker, 1)[1].strip()
            if new_content.startswith("```"):
                new_content = new_content.split("```", 1)[1].split("```", 1)[0].strip()
            return new_content, None
        else:
            return None, "Marker not found in response"
    except Exception as e:
        return None, str(e)

def git_commit_and_push():
    subprocess.run(["git", "checkout", "-b", NEW_BRANCH], cwd=WORKSPACE, check=True)
    subprocess.run(["git", "add", "."], cwd=WORKSPACE, check=True)
    subprocess.run(["git", "commit", "-m", "Gemini systemic improvements"], cwd=WORKSPACE, check=True)
    subprocess.run(["git", "push", "origin", NEW_BRANCH, "--force"], cwd=WORKSPACE, check=True)
    print(f"Pushed branch {NEW_BRANCH}")

def create_pr():
    if not GITHUB_TOKEN or not REPO_FULL_NAME:
        print("Missing GitHub token or repo name, cannot create PR automatically.")
        return
    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(REPO_FULL_NAME)
        pr = repo.create_pull(
            title="[AI] Gemini systemic code review & fixes",
            body="This PR was generated by an automated Gemini script. It reviewed all files and applied logic refinements.\n\nPlease verify carefully before merging.",
            head=NEW_BRANCH,
            base=BASE_BRANCH
        )
        print(f"Pull Request created: {pr.html_url}")
    except GithubException as e:
        print(f"Failed to create PR: {e}")

def main():
    if not GEMINI_API_KEY:
        print("ERROR: GEMINI_API_KEY environment variable not set")
        sys.exit(1)

    genai.configure(api_key=GEMINI_API_KEY)

    # Discover available model
    model_name = get_available_model()
    print(f"Using model: {model_name}")

    print("Discovering source files...")
    files = find_source_files(WORKSPACE)
    print(f"Found {len(files)} files.")

    changes_made = 0
    for idx, rel_path in enumerate(files, 1):
        print(f"[{idx}/{len(files)}] Reviewing {rel_path}...")
        content = read_file_content(rel_path)
        if content is None:
            continue
        new_content, error = review_and_fix_file(rel_path, content, model_name)
        if error:
            print(f"  Error: {error}")
            continue
        if new_content is None:
            print("  No response, skipping")
            continue
        if new_content.strip() != content.strip():
            print("  Changes detected – applying")
            write_file_content(rel_path, new_content)
            changes_made += 1
        else:
            print("  No changes needed")
        time.sleep(0.5)

    if changes_made == 0:
        print("No changes were generated. Exiting without creating PR.")
        sys.exit(0)

    print(f"Applied changes to {changes_made} files.")
    print("Committing and pushing branch...")
    git_commit_and_push()
    print("Creating Pull Request...")
    create_pr()

if __name__ == "__main__":
    main()